name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5
          php_version: 8.0
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit_coverage.xml
          args: --coverage-text /tests
        env:
          XDEBUG_MODE: coverage
